Adding volume tests to integration tests

diff --git a/src/test/integration/integration-test b/src/test/integration/integration-test
--- a/src/test/integration/integration-test
+++ b/src/test/integration/integration-test
@@ -6,6 +6,7 @@ sleepTimeSecs=10
 baseUrl=http://localhost:8080/
 computesEndpoint=computes/
 networksEndpoint=networks/
+volumesEndpoint=volumes/
 
 okHttpStatus=200
 noContentHttpStatus=204
@@ -58,7 +59,7 @@ function testGetNonExistentCompute {
     echo "Test ok."
     return 0
   fi
-  echo "Test failed, expected $notFoundHttpStatus error, but got:" $responseStatus
+  echo "Test failed, expected $notFoundHttpStatus status, but got:" $responseStatus
   return 1
 }
 
@@ -70,7 +71,7 @@ function testGetAllNonExistentCompute {
     echo "Test ok."
     return 0
   fi
-  echo "Test failed, expected $okHttpStatus error, but got:" $responseStatus
+  echo "Test failed, expected $okHttpStatus status, but got:" $responseStatus
   return 1
 }
 
@@ -120,7 +121,7 @@ function testDeleteCompute {
   if [ $deleteStatus -eq $noContentHttpStatus ]; then
     echo "Delete status was the expected:" $deleteStatus
   else
-    echo "Test failed, expected $noContentHttpStatus error, but got:" $deleteStatus
+    echo "Test failed, expected $noContentHttpStatus status, but got:" $deleteStatus
     #return 1
   fi
   echo "Testing if the instance can still be retrieved"
@@ -129,7 +130,7 @@ function testDeleteCompute {
     echo "Test ok."
     return 0
   fi
-  echo "Test failed, expected $notFoundHttpStatus error, but got:" $getInstanceStatus
+  echo "Test failed, expected $notFoundHttpStatus status, but got:" $getInstanceStatus
   return 1
 }
 
@@ -140,7 +141,7 @@ function testDeleteNonExistentCompute {
     echo "Test ok."
     return 0
   fi
-  echo "Test failed, expected $notFoundHttpStatus error, but got:" $deleteStatus
+  echo "Test failed, expected $notFoundHttpStatus status, but got:" $deleteStatus
   return 1
 }
 
@@ -169,7 +170,7 @@ function testDeleteNetwork {
   if [ $deleteStatus -eq $noContentHttpStatus ]; then
     echo "Delete status was the expected:" $deleteStatus
   else
-    echo "Test failed, expected $noContentHttpStatus error, but got:" $deleteStatus
+    echo "Test failed, expected $noContentHttpStatus status, but got:" $deleteStatus
     #return 1
   fi
   echo "Testing if the instance can still be retrieved"
@@ -178,7 +179,7 @@ function testDeleteNetwork {
     echo "Test ok."
     return 0
   fi
-  echo "Test failed, expected $notFoundHttpStatus error, but got:" $getInstanceStatus
+  echo "Test failed, expected $notFoundHttpStatus status, but got:" $getInstanceStatus
   return 1
 }
 
@@ -190,7 +191,7 @@ function testDeleteNonExistentNetwork {
     echo "Test ok."
     return 0
   fi
-  echo "Test failed, expected $notFoundHttpStatus error, but got:" $deleteStatus
+  echo "Test failed, expected $notFoundHttpStatus status, but got:" $deleteStatus
   return 1
 }
 
@@ -245,7 +246,7 @@ function testGetNonExistentNetwork {
       echo "Test ok."
     return 0
   fi
-  echo "Test failed, expected $notFoundHttpStatus error, but got:" $responseStatus
+  echo "Test failed, expected $notFoundHttpStatus status, but got:" $responseStatus
   return 1
 }
 
@@ -261,46 +262,148 @@ function doGetNetworkReturningStatus {
   echo $responseStatus
 }
 
+## Volume Tests
+
+### Delete volume functions
+
+function testDeleteVolume {
+  local instanceId=$(doPostVolume)
+  echo "Testing delete volume"
+  local deleteStatus=$(doDeleteVolumeReturningStatus $instanceId)
+  sleep $sleepTimeSecs
+  if [ $deleteStatus -eq $noContentHttpStatus ]; then
+    echo "Delete status was the expected:" $deleteStatus
+  else
+    echo "Test failed, expected $noContentHttpStatus status, but got:" $deleteStatus
+    #return 1
+  fi
+  echo "Testing if the instance can still be retrieved"
+  getInstanceStatus=$(doGetVolumeReturningStatus $instanceId)
+  if [ $getInstanceStatus -eq $notFoundHttpStatus ]; then
+    echo "Test ok."
+    return 0
+  fi
+  echo "Test failed, expected $notFoundHttpStatus status, but got:" $getInstanceStatus
+  return 1
+}
+
+function testDeleteNonExistentVolume {
+  local fakeInstanceId="non-existent-instance-id"
+  deleteStatus=$(doDeleteVolumeReturningStatus $fakeInstanceId)
+  sleep $sleepTimeSecs
+  if [ $deleteStatus -eq $notFoundHttpStatus ]; then
+    echo "Test ok."
+    return 0
+  fi
+  echo "Test failed, expected $notFoundHttpStatus status, but got:" $deleteStatus
+  return 1
+}
+
+function doDeleteVolume {
+  local instanceId=$1
+  $(curl -X DELETE -H "Content-Type: application/json" -H "federationTokenValue: token" $baseUrl$volumesEndpoint$instanceId 2> /dev/null)
+}
+
+function doDeleteVolumeReturningStatus {
+  local instanceId=$1
+  local responseStatus=$(curl -I -X DELETE -H "Content-Type: application/json" -H "federationTokenValue: token" $baseUrl$volumesEndpoint$instanceId 2> /dev/null | grep HTTP | awk '{print $2}')
+  echo $responseStatus
+}
+
+### Post volume functions
+
+function testPostVolume {
+  local instanceId=$(doPostVolume)
+  for try in `seq 1 $maxTries`
+  do
+    echo "Get volume. Try:" $try/$maxTries 
+    getInstanceResponse=$(doGetVolume $instanceId)
+    echo ${getInstanceResponse} | grep READY
+    if [ $? -eq 0 ]; then
+      echo "Test ok. Deleting volume..."
+      $(doDeleteVolume $instanceId)
+      return 0
+    fi
+    sleep $sleepTimeSecs
+  done
+  echo "Error when retrieving the volume created"
+  $(doDeleteVolume $instanceId)
+  return 1
+}
+
+function doPostVolume {
+  local response=$(curl -X POST -H "Content-Type: application/json" -H "federationTokenValue: token" -d \
+  '{
+    "volumeSize" : 2
+  }' $baseUrl$volumesEndpoint 2> /dev/null)
+  echo $response
+}
+
+### Get volume functions
+
+function testGetNonExistentVolume {
+  local fakeInstanceId="non-existent-instance-id"
+  local responseStatus=$(doGetVolumeReturningStatus $fakeInstanceId)
+  if [ $responseStatus -eq $notFoundHttpStatus ]; then
+      echo "Test ok."
+    return 0
+  fi
+  echo "Test failed, expected $notFoundHttpStatus status, but got:" $responseStatus
+  return 1
+}
+
+function doGetVolume {
+  local instanceId=$1
+  local response=$(curl -H "Content-Type: application/json" -H "federationTokenValue: token" $baseUrl$volumesEndpoint$instanceId 2> /dev/null)
+  echo $response
+}
+
+function doGetVolumeReturningStatus {
+  local instanceId=$1
+  local responseStatus=$(curl -I -H "Content-Type: application/json" -H "federationTokenValue: token" $baseUrl$volumesEndpoint$instanceId 2> /dev/null | grep HTTP | awk '{print $2}')
+  echo $responseStatus
+}
+
 ## Main
 
 function main {
   echo "============ Testing Compute ============"
-  echo "### Testing POST compute ###"
+  echo "### POST compute ###"
   testPostCompute
-  echo "### Testing POST compute with a new network ###"
+  #echo "### POST compute with a new network ###"
   #testPostComputeWithNetwork
-  echo "### Testing GET ALL non-existent compute ###"
+  echo "### GET ALL non-existent compute ###"
   testGetAllNonExistentCompute
-  echo "### Testing GET ALL compute ###"
+  echo "### GET ALL compute ###"
   testGetAllCompute
-  echo "### Testing GET non-existent compute ###"
+  echo "### GET non-existent compute ###"
   testGetNonExistentCompute
-  echo "### Testing DELETE compute ###"
+  echo "### DELETE compute ###"
   testDeleteCompute
-  echo "### Testing DELETE non-existent compute ###"
+  echo "### DELETE non-existent compute ###"
   testDeleteNonExistentCompute
 
   echo "============ Testing Network ============"
 
-  echo "### Testing POST network ###"
+  echo "### POST network ###"
   testPostNetwork
-  echo "### Testing GET non-existent network ###"
+  echo "### GET non-existent network ###"
   testGetNonExistentNetwork
-  echo "### Testing DELETE network ###"
+  echo "### DELETE network ###"
   testDeleteNetwork
-  echo "### Testing DELETE non-existent network ###"
+  echo "### DELETE non-existent network ###"
   testDeleteNonExistentNetwork
 
-  #echo "============ Testing Volume ============"
-#
-  #echo "### Testing POST volume ###"
-  #testPostNetwork
-  #echo "### Testing GET non-existent volume ###"
-  #testGetNonExistentNetwork
-  #echo "### Testing DELETE volume ###"
-  #testDeleteNetwork
-  #echo "### Testing DELETE non-existent volume ###"
-  #testDeleteNonExistentNetwork
+  echo "============ Testing Volume ============"
+
+  echo "### POST volume ###"
+  testPostVolume
+  echo "### GET non-existent volume ###"
+  testGetNonExistentVolume
+  echo "### DELETE volume ###"
+  testDeleteVolume
+  echo "### DELETE non-existent volume ###"
+  testDeleteNonExistentVolume
 }
 
 main
